"""お題の語彙。

選定基準は「カタカナ語を一切使わずに日本語で説明しきれること」。
説明の逃げ道が無い語 (固有名詞・商標) は入れない。

difficulty の目安:
  easy   … 具体物で、見た目や用途をそのまま述べれば伝わる
  normal … 言い換えに一手間かかる、または身近だが説明が長くなる
  hard   … 形の無い概念で、周辺から攻めるしかない
"""

WORD_ENTRIES: list[dict] = [
    # 食べ物・飲み物
    {"id": "w001", "word": "アイスクリーム", "difficulty": "easy", "tags": ["食べ物"]},
    {"id": "w002", "word": "ハンバーガー", "difficulty": "easy", "tags": ["食べ物"]},
    {"id": "w003", "word": "チョコレート", "difficulty": "easy", "tags": ["食べ物"]},
    {"id": "w004", "word": "コーヒー", "difficulty": "easy", "tags": ["食べ物"]},
    {"id": "w005", "word": "サラダ", "difficulty": "easy", "tags": ["食べ物"]},
    {"id": "w006", "word": "スープ", "difficulty": "easy", "tags": ["食べ物"]},
    {"id": "w007", "word": "ピザ", "difficulty": "easy", "tags": ["食べ物"]},
    {"id": "w008", "word": "サンドイッチ", "difficulty": "easy", "tags": ["食べ物"]},
    {"id": "w009", "word": "ヨーグルト", "difficulty": "easy", "tags": ["食べ物"]},
    {"id": "w010", "word": "ドーナツ", "difficulty": "easy", "tags": ["食べ物"]},
    {"id": "w011", "word": "ガム", "difficulty": "easy", "tags": ["食べ物"]},
    {"id": "w012", "word": "ジュース", "difficulty": "easy", "tags": ["食べ物"]},
    {"id": "w013", "word": "パスタ", "difficulty": "normal", "tags": ["食べ物"]},
    {"id": "w014", "word": "オムライス", "difficulty": "normal", "tags": ["食べ物", "和製英語"]},
    {"id": "w015", "word": "ハンバーグ", "difficulty": "normal", "tags": ["食べ物"]},
    {"id": "w016", "word": "マヨネーズ", "difficulty": "normal", "tags": ["食べ物"]},
    {"id": "w017", "word": "ケチャップ", "difficulty": "normal", "tags": ["食べ物"]},
    {"id": "w018", "word": "バター", "difficulty": "normal", "tags": ["食べ物"]},
    {"id": "w019", "word": "チーズ", "difficulty": "normal", "tags": ["食べ物"]},
    {"id": "w020", "word": "ソーセージ", "difficulty": "normal", "tags": ["食べ物"]},
    {"id": "w021", "word": "バイキング", "difficulty": "normal", "tags": ["食べ物", "和製英語"]},
    {"id": "w022", "word": "デザート", "difficulty": "normal", "tags": ["食べ物"]},
    {"id": "w023", "word": "レシピ", "difficulty": "hard", "tags": ["食べ物"]},
    {"id": "w024", "word": "カロリー", "difficulty": "hard", "tags": ["食べ物"]},
    {"id": "w025", "word": "グルメ", "difficulty": "hard", "tags": ["食べ物"]},
    # 家電・日用品
    {"id": "w026", "word": "テレビ", "difficulty": "easy", "tags": ["家電"]},
    {"id": "w027", "word": "カメラ", "difficulty": "easy", "tags": ["家電"]},
    {"id": "w028", "word": "パソコン", "difficulty": "easy", "tags": ["家電", "和製英語"]},
    {"id": "w029", "word": "エアコン", "difficulty": "easy", "tags": ["家電", "和製英語"]},
    {"id": "w030", "word": "ドライヤー", "difficulty": "easy", "tags": ["家電"]},
    {"id": "w031", "word": "ラジオ", "difficulty": "easy", "tags": ["家電"]},
    {"id": "w032", "word": "タオル", "difficulty": "easy", "tags": ["日用品"]},
    {"id": "w033", "word": "カーテン", "difficulty": "easy", "tags": ["日用品"]},
    {"id": "w034", "word": "ソファ", "difficulty": "easy", "tags": ["家具"]},
    {"id": "w035", "word": "テーブル", "difficulty": "easy", "tags": ["家具"]},
    {"id": "w036", "word": "ベッド", "difficulty": "easy", "tags": ["家具"]},
    {"id": "w037", "word": "コップ", "difficulty": "easy", "tags": ["日用品"]},
    {"id": "w038", "word": "スプーン", "difficulty": "easy", "tags": ["日用品"]},
    {"id": "w039", "word": "ハサミ", "difficulty": "easy", "tags": ["日用品"]},
    {"id": "w040", "word": "ノート", "difficulty": "easy", "tags": ["文房具"]},
    {"id": "w041", "word": "カレンダー", "difficulty": "easy", "tags": ["日用品"]},
    {"id": "w042", "word": "コンセント", "difficulty": "normal", "tags": ["家電", "和製英語"]},
    {"id": "w043", "word": "リモコン", "difficulty": "normal", "tags": ["家電", "和製英語"]},
    {"id": "w044", "word": "スイッチ", "difficulty": "normal", "tags": ["家電"]},
    {"id": "w045", "word": "ヘッドホン", "difficulty": "normal", "tags": ["家電"]},
    {"id": "w046", "word": "アイロン", "difficulty": "normal", "tags": ["家電"]},
    {"id": "w047", "word": "ミシン", "difficulty": "normal", "tags": ["家電"]},
    {"id": "w048", "word": "レンジ", "difficulty": "normal", "tags": ["家電"]},
    {"id": "w049", "word": "トースター", "difficulty": "normal", "tags": ["家電"]},
    {"id": "w050", "word": "スリッパ", "difficulty": "normal", "tags": ["日用品"]},
    {"id": "w051", "word": "ハンガー", "difficulty": "normal", "tags": ["日用品"]},
    {"id": "w052", "word": "クッション", "difficulty": "normal", "tags": ["日用品"]},
    {"id": "w053", "word": "シャンプー", "difficulty": "normal", "tags": ["日用品"]},
    # 乗り物・交通
    {"id": "w054", "word": "バス", "difficulty": "easy", "tags": ["乗り物"]},
    {"id": "w055", "word": "タクシー", "difficulty": "easy", "tags": ["乗り物"]},
    {"id": "w056", "word": "トラック", "difficulty": "easy", "tags": ["乗り物"]},
    {"id": "w057", "word": "ヘリコプター", "difficulty": "easy", "tags": ["乗り物"]},
    {"id": "w058", "word": "ロケット", "difficulty": "easy", "tags": ["乗り物"]},
    {"id": "w059", "word": "エレベーター", "difficulty": "easy", "tags": ["乗り物"]},
    {"id": "w060", "word": "エスカレーター", "difficulty": "easy", "tags": ["乗り物"]},
    {"id": "w061", "word": "ヘルメット", "difficulty": "easy", "tags": ["乗り物"]},
    {"id": "w062", "word": "タイヤ", "difficulty": "easy", "tags": ["乗り物"]},
    {"id": "w063", "word": "トンネル", "difficulty": "easy", "tags": ["乗り物"]},
    {"id": "w064", "word": "ハンドル", "difficulty": "normal", "tags": ["乗り物"]},
    {"id": "w065", "word": "ブレーキ", "difficulty": "normal", "tags": ["乗り物"]},
    {"id": "w066", "word": "ガソリン", "difficulty": "normal", "tags": ["乗り物"]},
    {"id": "w067", "word": "シートベルト", "difficulty": "normal", "tags": ["乗り物"]},
    {"id": "w068", "word": "ドライブ", "difficulty": "normal", "tags": ["乗り物"]},
    {"id": "w069", "word": "ラッシュアワー", "difficulty": "hard", "tags": ["乗り物"]},
    {"id": "w070", "word": "ナビゲーション", "difficulty": "hard", "tags": ["乗り物"]},
    # スポーツ
    {"id": "w071", "word": "サッカー", "difficulty": "easy", "tags": ["スポーツ"]},
    {"id": "w072", "word": "テニス", "difficulty": "easy", "tags": ["スポーツ"]},
    {"id": "w073", "word": "マラソン", "difficulty": "easy", "tags": ["スポーツ"]},
    {"id": "w074", "word": "スキー", "difficulty": "easy", "tags": ["スポーツ"]},
    {"id": "w075", "word": "プール", "difficulty": "easy", "tags": ["スポーツ"]},
    {"id": "w076", "word": "ゴール", "difficulty": "easy", "tags": ["スポーツ"]},
    {"id": "w077", "word": "チーム", "difficulty": "easy", "tags": ["スポーツ"]},
    {"id": "w078", "word": "メダル", "difficulty": "easy", "tags": ["スポーツ"]},
    {"id": "w079", "word": "コーチ", "difficulty": "normal", "tags": ["スポーツ"]},
    {"id": "w080", "word": "トロフィー", "difficulty": "normal", "tags": ["スポーツ"]},
    {"id": "w081", "word": "ストレッチ", "difficulty": "normal", "tags": ["スポーツ"]},
    {"id": "w082", "word": "ラケット", "difficulty": "normal", "tags": ["スポーツ"]},
    {"id": "w083", "word": "ゴーグル", "difficulty": "normal", "tags": ["スポーツ"]},
    {"id": "w084", "word": "ドリブル", "difficulty": "normal", "tags": ["スポーツ"]},
    {"id": "w085", "word": "リレー", "difficulty": "normal", "tags": ["スポーツ"]},
    {"id": "w086", "word": "ハードル", "difficulty": "normal", "tags": ["スポーツ"]},
    {"id": "w087", "word": "トーナメント", "difficulty": "hard", "tags": ["スポーツ"]},
    {"id": "w088", "word": "ペナルティ", "difficulty": "hard", "tags": ["スポーツ"]},
    # 服・身の回り
    {"id": "w089", "word": "シャツ", "difficulty": "easy", "tags": ["服"]},
    {"id": "w090", "word": "スカート", "difficulty": "easy", "tags": ["服"]},
    {"id": "w091", "word": "コート", "difficulty": "easy", "tags": ["服"]},
    {"id": "w092", "word": "セーター", "difficulty": "easy", "tags": ["服"]},
    {"id": "w093", "word": "ジーンズ", "difficulty": "easy", "tags": ["服"]},
    {"id": "w094", "word": "ポケット", "difficulty": "easy", "tags": ["服"]},
    {"id": "w095", "word": "リボン", "difficulty": "easy", "tags": ["服"]},
    {"id": "w096", "word": "ネックレス", "difficulty": "easy", "tags": ["服"]},
    {"id": "w097", "word": "サングラス", "difficulty": "easy", "tags": ["服"]},
    {"id": "w098", "word": "スニーカー", "difficulty": "easy", "tags": ["服"]},
    {"id": "w099", "word": "ブーツ", "difficulty": "easy", "tags": ["服"]},
    {"id": "w100", "word": "マフラー", "difficulty": "easy", "tags": ["服"]},
    {"id": "w101", "word": "ワンピース", "difficulty": "normal", "tags": ["服"]},
    {"id": "w102", "word": "カーディガン", "difficulty": "normal", "tags": ["服"]},
    {"id": "w103", "word": "ネクタイ", "difficulty": "normal", "tags": ["服"]},
    {"id": "w104", "word": "ベルト", "difficulty": "normal", "tags": ["服"]},
    {"id": "w105", "word": "ピアス", "difficulty": "normal", "tags": ["服"]},
    {"id": "w106", "word": "ファスナー", "difficulty": "normal", "tags": ["服"]},
    {"id": "w107", "word": "ブランド", "difficulty": "hard", "tags": ["服", "抽象"]},
    {"id": "w108", "word": "コーディネート", "difficulty": "hard", "tags": ["服"]},
    # 仕事・道具
    {"id": "w109", "word": "メール", "difficulty": "easy", "tags": ["仕事"]},
    {"id": "w110", "word": "インターネット", "difficulty": "easy", "tags": ["仕事"]},
    {"id": "w111", "word": "パスワード", "difficulty": "easy", "tags": ["仕事"]},
    {"id": "w112", "word": "プリンター", "difficulty": "easy", "tags": ["仕事"]},
    {"id": "w113", "word": "マウス", "difficulty": "normal", "tags": ["仕事"]},
    {"id": "w114", "word": "キーボード", "difficulty": "normal", "tags": ["仕事"]},
    {"id": "w115", "word": "アプリ", "difficulty": "normal", "tags": ["仕事"]},
    {"id": "w116", "word": "ダウンロード", "difficulty": "normal", "tags": ["仕事"]},
    {"id": "w117", "word": "クリック", "difficulty": "normal", "tags": ["仕事"]},
    {"id": "w118", "word": "アカウント", "difficulty": "normal", "tags": ["仕事"]},
    {"id": "w119", "word": "データ", "difficulty": "normal", "tags": ["仕事"]},
    {"id": "w120", "word": "ウイルス", "difficulty": "normal", "tags": ["仕事"]},
    {"id": "w121", "word": "バックアップ", "difficulty": "normal", "tags": ["仕事"]},
    {"id": "w122", "word": "スケジュール", "difficulty": "normal", "tags": ["仕事"]},
    {"id": "w123", "word": "アルバイト", "difficulty": "normal", "tags": ["仕事"]},
    {"id": "w124", "word": "サラリーマン", "difficulty": "normal", "tags": ["仕事", "和製英語"]},
    {"id": "w125", "word": "マニュアル", "difficulty": "normal", "tags": ["仕事"]},
    {"id": "w126", "word": "ノルマ", "difficulty": "hard", "tags": ["仕事"]},
    {"id": "w127", "word": "プレゼン", "difficulty": "hard", "tags": ["仕事"]},
    {"id": "w128", "word": "セキュリティ", "difficulty": "hard", "tags": ["仕事"]},
    {"id": "w129", "word": "キャリア", "difficulty": "hard", "tags": ["仕事"]},
    # 娯楽・音楽
    {"id": "w130", "word": "ピアノ", "difficulty": "easy", "tags": ["音楽"]},
    {"id": "w131", "word": "ギター", "difficulty": "easy", "tags": ["音楽"]},
    {"id": "w132", "word": "マイク", "difficulty": "easy", "tags": ["音楽"]},
    {"id": "w133", "word": "アニメ", "difficulty": "easy", "tags": ["娯楽"]},
    {"id": "w134", "word": "ゲーム", "difficulty": "easy", "tags": ["娯楽"]},
    {"id": "w135", "word": "チケット", "difficulty": "easy", "tags": ["娯楽"]},
    {"id": "w136", "word": "パーティー", "difficulty": "easy", "tags": ["娯楽"]},
    {"id": "w137", "word": "プレゼント", "difficulty": "easy", "tags": ["娯楽"]},
    {"id": "w138", "word": "キャンプ", "difficulty": "easy", "tags": ["娯楽"]},
    {"id": "w139", "word": "コンサート", "difficulty": "normal", "tags": ["音楽"]},
    {"id": "w140", "word": "カラオケ", "difficulty": "normal", "tags": ["娯楽", "和製英語"]},
    {"id": "w141", "word": "バーベキュー", "difficulty": "normal", "tags": ["娯楽"]},
    {
        "id": "w142",
        "word": "ジェットコースター",
        "difficulty": "normal",
        "tags": ["娯楽", "和製英語"],
    },
    # 形の無いもの
    {"id": "w143", "word": "ルール", "difficulty": "normal", "tags": ["抽象"]},
    {"id": "w144", "word": "アイデア", "difficulty": "normal", "tags": ["抽象"]},
    {"id": "w145", "word": "チャンス", "difficulty": "normal", "tags": ["抽象"]},
    {"id": "w146", "word": "バランス", "difficulty": "normal", "tags": ["抽象"]},
    {"id": "w147", "word": "タイミング", "difficulty": "normal", "tags": ["抽象"]},
    {"id": "w148", "word": "スピード", "difficulty": "normal", "tags": ["抽象"]},
    {"id": "w149", "word": "エネルギー", "difficulty": "normal", "tags": ["抽象"]},
    {"id": "w150", "word": "レベル", "difficulty": "normal", "tags": ["抽象"]},
    {"id": "w151", "word": "サイン", "difficulty": "normal", "tags": ["抽象"]},
    {"id": "w152", "word": "グループ", "difficulty": "normal", "tags": ["抽象"]},
    {"id": "w153", "word": "ストレス", "difficulty": "hard", "tags": ["抽象"]},
    {"id": "w154", "word": "イメージ", "difficulty": "hard", "tags": ["抽象"]},
    {"id": "w155", "word": "ユーモア", "difficulty": "hard", "tags": ["抽象"]},
    {"id": "w156", "word": "プレッシャー", "difficulty": "hard", "tags": ["抽象"]},
    {"id": "w157", "word": "モチベーション", "difficulty": "hard", "tags": ["抽象"]},
    {"id": "w158", "word": "センス", "difficulty": "hard", "tags": ["抽象"]},
    {"id": "w159", "word": "プライド", "difficulty": "hard", "tags": ["抽象"]},
    {"id": "w160", "word": "デジャヴ", "difficulty": "hard", "tags": ["抽象"]},
]
